[env:esp32dev]
platform = espressif32 @ 6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    https://github.com/blackketter/ESP32-BLE-Combo.git
    bblanchon/ArduinoJson@^7
board_build.partitions = huge_app.csv